/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface BlogPostInput {
    title: string;
    content: string;
    categoryTags: Array<string>;
    publishDate?: Timestamp;
    featuredImage: ExternalBlob;
    slug: string;
    postStatus: PostStatus;
    description: string;
    author: string;
}
export interface BlogPage {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    posts: Array<BlogPost>;
}
export interface VehicleFilter {
    vehicleType?: VehicleType;
}
export interface Vehicle {
    id: Id;
    model: string;
    vehicleType: VehicleType;
    title: string;
    featured: boolean;
    createdAt: Timestamp;
    description: string;
    pricePerDay: bigint;
    updatedAt: Timestamp;
    capacity: bigint;
    images: Array<ExternalBlob>;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Property {
    id: Id;
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    bedrooms: bigint;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    location: string;
    images: Array<ExternalBlob>;
}
export interface CompanySettings {
    whatsapp: string;
    instagramUrl?: string;
    email: string;
    logoUrl: string;
    address: string;
    phone: string;
    youtubeUrl?: string;
    facebookUrl?: string;
    linkedinUrl?: string;
}
export interface Booking {
    id: Id;
    customerName: string;
    status: BookingStatus;
    endDate: string;
    specialRequests: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    phone: string;
    vehicleId: Id;
    startDate: string;
}
export interface Quote {
    id: Id;
    customerName: string;
    status: QuoteStatus;
    serviceType: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    phone: string;
    requirements: string;
    budgetRange: string;
}
export interface QuoteInput {
    customerName: string;
    serviceType: string;
    email: string;
    phone: string;
    requirements: string;
    budgetRange: string;
}
export interface PropertyFilter {
    propertyType?: PropertyType;
    maxPrice?: bigint;
    minPrice?: bigint;
}
export interface BlogPost {
    id: Id;
    title: string;
    content: string;
    categoryTags: Array<string>;
    publishDate?: Timestamp;
    featuredImage: ExternalBlob;
    createdAt: Timestamp;
    slug: string;
    postStatus: PostStatus;
    description: string;
    author: string;
    updatedAt: Timestamp;
}
export interface TrainingInput {
    durationDays: bigint;
    title: string;
    maxCapacity: bigint;
    description: string;
    image: ExternalBlob;
    price: bigint;
}
export interface VehicleInput {
    model: string;
    vehicleType: VehicleType;
    title: string;
    featured: boolean;
    description: string;
    pricePerDay: bigint;
    capacity: bigint;
    images: Array<ExternalBlob>;
}
export interface EnrollmentInput {
    name: string;
    email: string;
    trainingId: Id;
    phone: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BookingInput {
    customerName: string;
    endDate: string;
    specialRequests: string;
    email: string;
    phone: string;
    vehicleId: Id;
    startDate: string;
}
export interface TrainingEnrollment {
    dateRegistered: Timestamp;
    name: string;
    email: string;
    phone: string;
}
export interface DashboardStats {
    pendingBookings: bigint;
    totalProperties: bigint;
    totalTrainings: bigint;
    totalVehicles: bigint;
    totalBlogPosts: bigint;
    unreadMessages: bigint;
    totalBookings: bigint;
    totalMessages: bigint;
    totalQuotes: bigint;
    totalSubscribers: bigint;
    pendingQuotes: bigint;
}
export interface PropertyInput {
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    bedrooms: bigint;
    description: string;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    location: string;
    images: Array<ExternalBlob>;
}
export interface Training {
    id: Id;
    durationDays: bigint;
    title: string;
    maxCapacity: bigint;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    image: ExternalBlob;
    price: bigint;
    enrollments: Array<TrainingEnrollment>;
}
export interface Message {
    id: Id;
    customerName: string;
    status: MessageStatus;
    createdAt: Timestamp;
    email: string;
    message: string;
    phone: string;
}
export type Id = bigint;
export interface NewsletterSubscriber {
    id: Id;
    unsubscribedAt?: Timestamp;
    verified: boolean;
    subscribedAt: Timestamp;
    email: string;
}
export interface MessageInput {
    customerName: string;
    email: string;
    message: string;
    phone: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum MessageStatus {
    read = "read",
    unread = "unread",
    archived = "archived"
}
export enum PostStatus {
    published = "published",
    draft = "draft"
}
export enum PropertyType {
    house = "house",
    land = "land",
    apartment = "apartment",
    office = "office"
}
export enum QuoteStatus {
    pending = "pending",
    sent = "sent",
    accepted = "accepted",
    declined = "declined"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleType {
    bus = "bus",
    car = "car",
    truck = "truck",
    minibus = "minibus"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    adminCreateBlogPost(input: BlogPostInput): Promise<BlogPost>;
    adminCreateProperty(input: PropertyInput): Promise<Property>;
    adminCreateTraining(input: TrainingInput): Promise<Training>;
    adminCreateVehicle(input: VehicleInput): Promise<Vehicle>;
    adminDeleteBlogPost(id: Id): Promise<boolean>;
    adminDeleteProperty(id: Id): Promise<boolean>;
    adminDeleteTraining(id: Id): Promise<boolean>;
    adminDeleteVehicle(id: Id): Promise<boolean>;
    adminGetActiveSubscriberCount(): Promise<bigint>;
    adminGetBookingById(id: Id): Promise<Booking | null>;
    adminGetDashboardStats(): Promise<DashboardStats>;
    adminGetEnrollmentsList(trainingId: Id): Promise<Array<TrainingEnrollment>>;
    adminGetPendingBookingCount(): Promise<bigint>;
    adminGetPendingQuoteCount(): Promise<bigint>;
    adminGetQuoteById(id: Id): Promise<Quote | null>;
    adminGetUnreadMessageCount(): Promise<bigint>;
    adminListBlogPosts(): Promise<Array<BlogPost>>;
    adminListBookings(): Promise<Array<Booking>>;
    adminListMessages(): Promise<Array<Message>>;
    adminListProperties(): Promise<Array<Property>>;
    adminListQuotes(): Promise<Array<Quote>>;
    adminListSubscribers(): Promise<Array<NewsletterSubscriber>>;
    adminListTrainings(): Promise<Array<Training>>;
    adminListVehicles(): Promise<Array<Vehicle>>;
    adminUpdateBlogPost(id: Id, input: BlogPostInput): Promise<BlogPost | null>;
    adminUpdateBookingStatus(id: Id, status: BookingStatus): Promise<Booking | null>;
    adminUpdateCompanySettings(settings: CompanySettings): Promise<void>;
    adminUpdateMessageStatus(id: Id, status: MessageStatus): Promise<Message | null>;
    adminUpdateProperty(id: Id, input: PropertyInput): Promise<Property | null>;
    adminUpdateQuoteStatus(id: Id, status: QuoteStatus): Promise<Quote | null>;
    adminUpdateTraining(id: Id, input: TrainingInput): Promise<Training | null>;
    adminUpdateVehicle(id: Id, input: VehicleInput): Promise<Vehicle | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    enrollInTraining(input: EnrollmentInput): Promise<boolean>;
    getBlogPostById(id: Id): Promise<BlogPost | null>;
    getBlogPostBySlug(slug: string): Promise<BlogPost | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanySettings(): Promise<CompanySettings>;
    getProperty(id: Id): Promise<Property | null>;
    getTraining(id: Id): Promise<Training | null>;
    getVehicle(id: Id): Promise<Vehicle | null>;
    isCallerAdmin(): Promise<boolean>;
    listBlogPosts(page: bigint, pageSize: bigint): Promise<BlogPage>;
    listProperties(filter: PropertyFilter): Promise<Array<Property>>;
    listTrainings(): Promise<Array<Training>>;
    listVehicles(filter: VehicleFilter): Promise<Array<Vehicle>>;
    submitBooking(input: BookingInput): Promise<Booking>;
    submitMessage(input: MessageInput): Promise<Message>;
    submitQuote(input: QuoteInput): Promise<Quote>;
    subscribeNewsletter(email: string): Promise<NewsletterSubscriber>;
    unsubscribeNewsletter(email: string): Promise<boolean>;
}
import type { BlogPage as _BlogPage, BlogPost as _BlogPost, BlogPostInput as _BlogPostInput, Booking as _Booking, BookingStatus as _BookingStatus, CompanySettings as _CompanySettings, ExternalBlob as _ExternalBlob, Id as _Id, Message as _Message, MessageStatus as _MessageStatus, NewsletterSubscriber as _NewsletterSubscriber, PostStatus as _PostStatus, Property as _Property, PropertyFilter as _PropertyFilter, PropertyInput as _PropertyInput, PropertyType as _PropertyType, Quote as _Quote, QuoteStatus as _QuoteStatus, Timestamp as _Timestamp, Training as _Training, TrainingEnrollment as _TrainingEnrollment, TrainingInput as _TrainingInput, UserRole as _UserRole, Vehicle as _Vehicle, VehicleFilter as _VehicleFilter, VehicleInput as _VehicleInput, VehicleType as _VehicleType, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminCreateBlogPost(arg0: BlogPostInput): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateBlogPost(await to_candid_BlogPostInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BlogPost_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateBlogPost(await to_candid_BlogPostInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BlogPost_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateProperty(arg0: PropertyInput): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateProperty(await to_candid_PropertyInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Property_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateProperty(await to_candid_PropertyInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Property_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateTraining(arg0: TrainingInput): Promise<Training> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateTraining(await to_candid_TrainingInput_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Training_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateTraining(await to_candid_TrainingInput_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Training_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateVehicle(arg0: VehicleInput): Promise<Vehicle> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateVehicle(await to_candid_VehicleInput_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Vehicle_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateVehicle(await to_candid_VehicleInput_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Vehicle_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteBlogPost(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteBlogPost(arg0);
            return result;
        }
    }
    async adminDeleteProperty(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProperty(arg0);
            return result;
        }
    }
    async adminDeleteTraining(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteTraining(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteTraining(arg0);
            return result;
        }
    }
    async adminDeleteVehicle(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteVehicle(arg0);
            return result;
        }
    }
    async adminGetActiveSubscriberCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetActiveSubscriberCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetActiveSubscriberCount();
            return result;
        }
    }
    async adminGetBookingById(arg0: Id): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetBookingById(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetBookingById(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDashboardStats();
            return result;
        }
    }
    async adminGetEnrollmentsList(arg0: Id): Promise<Array<TrainingEnrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetEnrollmentsList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetEnrollmentsList(arg0);
            return result;
        }
    }
    async adminGetPendingBookingCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingBookingCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingBookingCount();
            return result;
        }
    }
    async adminGetPendingQuoteCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingQuoteCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingQuoteCount();
            return result;
        }
    }
    async adminGetQuoteById(arg0: Id): Promise<Quote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetQuoteById(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetQuoteById(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUnreadMessageCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUnreadMessageCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUnreadMessageCount();
            return result;
        }
    }
    async adminListBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListBlogPosts();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListBlogPosts();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListBookings();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListBookings();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListMessages();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListMessages();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListProperties();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListProperties();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListQuotes(): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListQuotes();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListQuotes();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListSubscribers(): Promise<Array<NewsletterSubscriber>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListSubscribers();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListSubscribers();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListTrainings(): Promise<Array<Training>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListTrainings();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListTrainings();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListVehicles();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListVehicles();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateBlogPost(arg0: Id, arg1: BlogPostInput): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateBlogPost(arg0, await to_candid_BlogPostInput_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateBlogPost(arg0, await to_candid_BlogPostInput_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateBookingStatus(arg0: Id, arg1: BookingStatus): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateBookingStatus(arg0, to_candid_BookingStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateBookingStatus(arg0, to_candid_BookingStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateCompanySettings(arg0: CompanySettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateCompanySettings(to_candid_CompanySettings_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateCompanySettings(to_candid_CompanySettings_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminUpdateMessageStatus(arg0: Id, arg1: MessageStatus): Promise<Message | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateMessageStatus(arg0, to_candid_MessageStatus_n70(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateMessageStatus(arg0, to_candid_MessageStatus_n70(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateProperty(arg0: Id, arg1: PropertyInput): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProperty(arg0, await to_candid_PropertyInput_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProperty(arg0, await to_candid_PropertyInput_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateQuoteStatus(arg0: Id, arg1: QuoteStatus): Promise<Quote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateQuoteStatus(arg0, to_candid_QuoteStatus_n74(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateQuoteStatus(arg0, to_candid_QuoteStatus_n74(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateTraining(arg0: Id, arg1: TrainingInput): Promise<Training | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateTraining(arg0, await to_candid_TrainingInput_n29(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateTraining(arg0, await to_candid_TrainingInput_n29(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateVehicle(arg0: Id, arg1: VehicleInput): Promise<Vehicle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateVehicle(arg0, await to_candid_VehicleInput_n33(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateVehicle(arg0, await to_candid_VehicleInput_n33(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n78(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n78(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async enrollInTraining(arg0: EnrollmentInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInTraining(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInTraining(arg0);
            return result;
        }
    }
    async getBlogPostById(arg0: Id): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostById(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostById(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostBySlug(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostBySlug(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostBySlug(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanySettings(): Promise<CompanySettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanySettings();
                return from_candid_CompanySettings_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanySettings();
            return from_candid_CompanySettings_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: Id): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTraining(arg0: Id): Promise<Training | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTraining(arg0);
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTraining(arg0);
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: Id): Promise<Vehicle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listBlogPosts(arg0: bigint, arg1: bigint): Promise<BlogPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogPosts(arg0, arg1);
                return from_candid_BlogPage_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogPosts(arg0, arg1);
            return from_candid_BlogPage_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProperties(arg0: PropertyFilter): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProperties(to_candid_PropertyFilter_n87(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProperties(to_candid_PropertyFilter_n87(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrainings(): Promise<Array<Training>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrainings();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrainings();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVehicles(arg0: VehicleFilter): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVehicles(to_candid_VehicleFilter_n89(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVehicles(to_candid_VehicleFilter_n89(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitBooking(arg0: BookingInput): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0);
                return from_candid_Booking_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0);
            return from_candid_Booking_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitMessage(arg0: MessageInput): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMessage(arg0);
                return from_candid_Message_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMessage(arg0);
            return from_candid_Message_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuote(arg0: QuoteInput): Promise<Quote> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuote(arg0);
                return from_candid_Quote_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuote(arg0);
            return from_candid_Quote_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async subscribeNewsletter(arg0: string): Promise<NewsletterSubscriber> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeNewsletter(arg0);
                return from_candid_NewsletterSubscriber_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeNewsletter(arg0);
            return from_candid_NewsletterSubscriber_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async unsubscribeNewsletter(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unsubscribeNewsletter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsubscribeNewsletter(arg0);
            return result;
        }
    }
}
async function from_candid_BlogPage_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPage): Promise<BlogPage> {
    return await from_candid_record_n86(_uploadFile, _downloadFile, value);
}
async function from_candid_BlogPost_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_CompanySettings_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanySettings): CompanySettings {
    return from_candid_record_n83(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MessageStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_NewsletterSubscriber_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsletterSubscriber): NewsletterSubscriber {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_PostStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_Property_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Promise<Property> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_QuoteStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteStatus): QuoteStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Quote_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quote): Quote {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_Training_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Training): Promise<Training> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_Vehicle_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Promise<Vehicle> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quote]): Quote | null {
    return value.length === 0 ? null : from_candid_Quote_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): Promise<BlogPost | null> {
    return value.length === 0 ? null : await from_candid_BlogPost_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : from_candid_Message_n54(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Promise<Property | null> {
    return value.length === 0 ? null : await from_candid_Property_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Training]): Promise<Training | null> {
    return value.length === 0 ? null : await from_candid_Training_n31(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vehicle]): Promise<Vehicle | null> {
    return value.length === 0 ? null : await from_candid_Vehicle_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    content: string;
    categoryTags: Array<string>;
    publishDate: [] | [_Timestamp];
    featuredImage: _ExternalBlob;
    createdAt: _Timestamp;
    slug: string;
    postStatus: _PostStatus;
    description: string;
    author: string;
    updatedAt: _Timestamp;
}): Promise<{
    id: Id;
    title: string;
    content: string;
    categoryTags: Array<string>;
    publishDate?: Timestamp;
    featuredImage: ExternalBlob;
    createdAt: Timestamp;
    slug: string;
    postStatus: PostStatus;
    description: string;
    author: string;
    updatedAt: Timestamp;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        categoryTags: value.categoryTags,
        publishDate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.publishDate)),
        featuredImage: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.featuredImage),
        createdAt: value.createdAt,
        slug: value.slug,
        postStatus: from_candid_PostStatus_n17(_uploadFile, _downloadFile, value.postStatus),
        description: value.description,
        author: value.author,
        updatedAt: value.updatedAt
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    featured: boolean;
    propertyType: _PropertyType;
    bedrooms: bigint;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    location: string;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: Id;
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    bedrooms: bigint;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    location: string;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        propertyType: from_candid_PropertyType_n26(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        areaSqm: value.areaSqm,
        bathrooms: value.bathrooms,
        price: value.price,
        location: value.location,
        images: await from_candid_vec_n28(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    durationDays: bigint;
    title: string;
    maxCapacity: bigint;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    image: _ExternalBlob;
    price: bigint;
    enrollments: Array<_TrainingEnrollment>;
}): Promise<{
    id: Id;
    durationDays: bigint;
    title: string;
    maxCapacity: bigint;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    image: ExternalBlob;
    price: bigint;
    enrollments: Array<TrainingEnrollment>;
}> {
    return {
        id: value.id,
        durationDays: value.durationDays,
        title: value.title,
        maxCapacity: value.maxCapacity,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        image: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.image),
        price: value.price,
        enrollments: value.enrollments
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    model: string;
    vehicleType: _VehicleType;
    title: string;
    featured: boolean;
    createdAt: _Timestamp;
    description: string;
    pricePerDay: bigint;
    updatedAt: _Timestamp;
    capacity: bigint;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: Id;
    model: string;
    vehicleType: VehicleType;
    title: string;
    featured: boolean;
    createdAt: Timestamp;
    description: string;
    pricePerDay: bigint;
    updatedAt: Timestamp;
    capacity: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        model: value.model,
        vehicleType: from_candid_VehicleType_n39(_uploadFile, _downloadFile, value.vehicleType),
        title: value.title,
        featured: value.featured,
        createdAt: value.createdAt,
        description: value.description,
        pricePerDay: value.pricePerDay,
        updatedAt: value.updatedAt,
        capacity: value.capacity,
        images: await from_candid_vec_n28(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    customerName: string;
    status: _BookingStatus;
    endDate: string;
    specialRequests: string;
    createdAt: _Timestamp;
    email: string;
    updatedAt: _Timestamp;
    phone: string;
    vehicleId: _Id;
    startDate: string;
}): {
    id: Id;
    customerName: string;
    status: BookingStatus;
    endDate: string;
    specialRequests: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    phone: string;
    vehicleId: Id;
    startDate: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_BookingStatus_n44(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        specialRequests: value.specialRequests,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        phone: value.phone,
        vehicleId: value.vehicleId,
        startDate: value.startDate
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    customerName: string;
    status: _QuoteStatus;
    serviceType: string;
    createdAt: _Timestamp;
    email: string;
    updatedAt: _Timestamp;
    phone: string;
    requirements: string;
    budgetRange: string;
}): {
    id: Id;
    customerName: string;
    status: QuoteStatus;
    serviceType: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    phone: string;
    requirements: string;
    budgetRange: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_QuoteStatus_n49(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        phone: value.phone,
        requirements: value.requirements,
        budgetRange: value.budgetRange
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    customerName: string;
    status: _MessageStatus;
    createdAt: _Timestamp;
    email: string;
    message: string;
    phone: string;
}): {
    id: Id;
    customerName: string;
    status: MessageStatus;
    createdAt: Timestamp;
    email: string;
    message: string;
    phone: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_MessageStatus_n56(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    unsubscribedAt: [] | [_Timestamp];
    verified: boolean;
    subscribedAt: _Timestamp;
    email: string;
}): {
    id: Id;
    unsubscribedAt?: Timestamp;
    verified: boolean;
    subscribedAt: Timestamp;
    email: string;
} {
    return {
        id: value.id,
        unsubscribedAt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.unsubscribedAt)),
        verified: value.verified,
        subscribedAt: value.subscribedAt,
        email: value.email
    };
}
function from_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    whatsapp: string;
    instagramUrl: [] | [string];
    email: string;
    logoUrl: string;
    address: string;
    phone: string;
    youtubeUrl: [] | [string];
    facebookUrl: [] | [string];
    linkedinUrl: [] | [string];
}): {
    whatsapp: string;
    instagramUrl?: string;
    email: string;
    logoUrl: string;
    address: string;
    phone: string;
    youtubeUrl?: string;
    facebookUrl?: string;
    linkedinUrl?: string;
} {
    return {
        whatsapp: value.whatsapp,
        instagramUrl: record_opt_to_undefined(from_candid_opt_n84(_uploadFile, _downloadFile, value.instagramUrl)),
        email: value.email,
        logoUrl: value.logoUrl,
        address: value.address,
        phone: value.phone,
        youtubeUrl: record_opt_to_undefined(from_candid_opt_n84(_uploadFile, _downloadFile, value.youtubeUrl)),
        facebookUrl: record_opt_to_undefined(from_candid_opt_n84(_uploadFile, _downloadFile, value.facebookUrl)),
        linkedinUrl: record_opt_to_undefined(from_candid_opt_n84(_uploadFile, _downloadFile, value.linkedinUrl))
    };
}
async function from_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    posts: Array<_BlogPost>;
}): Promise<{
    total: bigint;
    page: bigint;
    pageSize: bigint;
    posts: Array<BlogPost>;
}> {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        posts: await from_candid_vec_n51(_uploadFile, _downloadFile, value.posts)
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): PostStatus {
    return "published" in value ? PostStatus.published : "draft" in value ? PostStatus.draft : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    house: null;
} | {
    land: null;
} | {
    apartment: null;
} | {
    office: null;
}): PropertyType {
    return "house" in value ? PropertyType.house : "land" in value ? PropertyType.land : "apartment" in value ? PropertyType.apartment : "office" in value ? PropertyType.office : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bus: null;
} | {
    car: null;
} | {
    truck: null;
} | {
    minibus: null;
}): VehicleType {
    return "bus" in value ? VehicleType.bus : "car" in value ? VehicleType.car : "truck" in value ? VehicleType.truck : "minibus" in value ? VehicleType.minibus : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sent: null;
} | {
    accepted: null;
} | {
    declined: null;
}): QuoteStatus {
    return "pending" in value ? QuoteStatus.pending : "sent" in value ? QuoteStatus.sent : "accepted" in value ? QuoteStatus.accepted : "declined" in value ? QuoteStatus.declined : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    read: null;
} | {
    unread: null;
} | {
    archived: null;
}): MessageStatus {
    return "read" in value ? MessageStatus.read : "unread" in value ? MessageStatus.unread : "archived" in value ? MessageStatus.archived : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n13(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n54(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Promise<Array<Property>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Property_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quote>): Array<Quote> {
    return value.map((x)=>from_candid_Quote_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsletterSubscriber>): Array<NewsletterSubscriber> {
    return value.map((x)=>from_candid_NewsletterSubscriber_n61(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Training>): Promise<Array<Training>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Training_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vehicle>): Promise<Array<Vehicle>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Vehicle_n37(_uploadFile, _downloadFile, x)));
}
async function to_candid_BlogPostInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPostInput): Promise<_BlogPostInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_CompanySettings_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanySettings): _CompanySettings {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MessageStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageStatus): _MessageStatus {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_PostStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): _PostStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyFilter_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyFilter): _PropertyFilter {
    return to_candid_record_n88(_uploadFile, _downloadFile, value);
}
async function to_candid_PropertyInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyInput): Promise<_PropertyInput> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_QuoteStatus_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteStatus): _QuoteStatus {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
async function to_candid_TrainingInput_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingInput): Promise<_TrainingInput> {
    return await to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n79(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleFilter_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleFilter): _VehicleFilter {
    return to_candid_record_n90(_uploadFile, _downloadFile, value);
}
async function to_candid_VehicleInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleInput): Promise<_VehicleInput> {
    return await to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    bedrooms: bigint;
    description: string;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    location: string;
    images: Array<ExternalBlob>;
}): Promise<{
    title: string;
    featured: boolean;
    propertyType: _PropertyType;
    bedrooms: bigint;
    description: string;
    areaSqm: bigint;
    bathrooms: bigint;
    price: bigint;
    location: string;
    images: Array<_ExternalBlob>;
}> {
    return {
        title: value.title,
        featured: value.featured,
        propertyType: to_candid_PropertyType_n21(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        description: value.description,
        areaSqm: value.areaSqm,
        bathrooms: value.bathrooms,
        price: value.price,
        location: value.location,
        images: await to_candid_vec_n23(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationDays: bigint;
    title: string;
    maxCapacity: bigint;
    description: string;
    image: ExternalBlob;
    price: bigint;
}): Promise<{
    durationDays: bigint;
    title: string;
    maxCapacity: bigint;
    description: string;
    image: _ExternalBlob;
    price: bigint;
}> {
    return {
        durationDays: value.durationDays,
        title: value.title,
        maxCapacity: value.maxCapacity,
        description: value.description,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
async function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: string;
    vehicleType: VehicleType;
    title: string;
    featured: boolean;
    description: string;
    pricePerDay: bigint;
    capacity: bigint;
    images: Array<ExternalBlob>;
}): Promise<{
    model: string;
    vehicleType: _VehicleType;
    title: string;
    featured: boolean;
    description: string;
    pricePerDay: bigint;
    capacity: bigint;
    images: Array<_ExternalBlob>;
}> {
    return {
        model: value.model,
        vehicleType: to_candid_VehicleType_n35(_uploadFile, _downloadFile, value.vehicleType),
        title: value.title,
        featured: value.featured,
        description: value.description,
        pricePerDay: value.pricePerDay,
        capacity: value.capacity,
        images: await to_candid_vec_n23(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    whatsapp: string;
    instagramUrl?: string;
    email: string;
    logoUrl: string;
    address: string;
    phone: string;
    youtubeUrl?: string;
    facebookUrl?: string;
    linkedinUrl?: string;
}): {
    whatsapp: string;
    instagramUrl: [] | [string];
    email: string;
    logoUrl: string;
    address: string;
    phone: string;
    youtubeUrl: [] | [string];
    facebookUrl: [] | [string];
    linkedinUrl: [] | [string];
} {
    return {
        whatsapp: value.whatsapp,
        instagramUrl: value.instagramUrl ? candid_some(value.instagramUrl) : candid_none(),
        email: value.email,
        logoUrl: value.logoUrl,
        address: value.address,
        phone: value.phone,
        youtubeUrl: value.youtubeUrl ? candid_some(value.youtubeUrl) : candid_none(),
        facebookUrl: value.facebookUrl ? candid_some(value.facebookUrl) : candid_none(),
        linkedinUrl: value.linkedinUrl ? candid_some(value.linkedinUrl) : candid_none()
    };
}
function to_candid_record_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyType?: PropertyType;
    maxPrice?: bigint;
    minPrice?: bigint;
}): {
    propertyType: [] | [_PropertyType];
    maxPrice: [] | [bigint];
    minPrice: [] | [bigint];
} {
    return {
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n21(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    categoryTags: Array<string>;
    publishDate?: Timestamp;
    featuredImage: ExternalBlob;
    slug: string;
    postStatus: PostStatus;
    description: string;
    author: string;
}): Promise<{
    title: string;
    content: string;
    categoryTags: Array<string>;
    publishDate: [] | [_Timestamp];
    featuredImage: _ExternalBlob;
    slug: string;
    postStatus: _PostStatus;
    description: string;
    author: string;
}> {
    return {
        title: value.title,
        content: value.content,
        categoryTags: value.categoryTags,
        publishDate: value.publishDate ? candid_some(value.publishDate) : candid_none(),
        featuredImage: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.featuredImage),
        slug: value.slug,
        postStatus: to_candid_PostStatus_n11(_uploadFile, _downloadFile, value.postStatus),
        description: value.description,
        author: value.author
    };
}
function to_candid_record_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vehicleType?: VehicleType;
}): {
    vehicleType: [] | [_VehicleType];
} {
    return {
        vehicleType: value.vehicleType ? candid_some(to_candid_VehicleType_n35(_uploadFile, _downloadFile, value.vehicleType)) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): {
    published: null;
} | {
    draft: null;
} {
    return value == PostStatus.published ? {
        published: null
    } : value == PostStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    house: null;
} | {
    land: null;
} | {
    apartment: null;
} | {
    office: null;
} {
    return value == PropertyType.house ? {
        house: null
    } : value == PropertyType.land ? {
        land: null
    } : value == PropertyType.apartment ? {
        apartment: null
    } : value == PropertyType.office ? {
        office: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    bus: null;
} | {
    car: null;
} | {
    truck: null;
} | {
    minibus: null;
} {
    return value == VehicleType.bus ? {
        bus: null
    } : value == VehicleType.car ? {
        car: null
    } : value == VehicleType.truck ? {
        truck: null
    } : value == VehicleType.minibus ? {
        minibus: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageStatus): {
    read: null;
} | {
    unread: null;
} | {
    archived: null;
} {
    return value == MessageStatus.read ? {
        read: null
    } : value == MessageStatus.unread ? {
        unread: null
    } : value == MessageStatus.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteStatus): {
    pending: null;
} | {
    sent: null;
} | {
    accepted: null;
} | {
    declined: null;
} {
    return value == QuoteStatus.pending ? {
        pending: null
    } : value == QuoteStatus.sent ? {
        sent: null
    } : value == QuoteStatus.accepted ? {
        accepted: null
    } : value == QuoteStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_variant_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
